//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllyisApps.Resources.Controllers.Auth {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AllyisApps.Resources.Controllers.Auth.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform this action..
        /// </summary>
        public static string ActionUnauthorizedMessage {
            get {
                return ResourceManager.GetString("ActionUnauthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing information accepted..
        /// </summary>
        public static string Billing {
            get {
                return ResourceManager.GetString("Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing information removed..
        /// </summary>
        public static string BillingRemoved {
            get {
                return ResourceManager.GetString("BillingRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are unable to edit the members of this organization..
        /// </summary>
        public static string CannotEditMembersMessage {
            get {
                return ResourceManager.GetString("CannotEditMembersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are unable edit this organization..
        /// </summary>
        public static string CannotEditProfileMessage {
            get {
                return ResourceManager.GetString("CannotEditProfileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot remove your billing information while you are still paying for subscriptions!.
        /// </summary>
        public static string CannotRemoveBilling {
            get {
                return ResourceManager.GetString("CannotRemoveBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string ChangePasswordSuccessMessage {
            get {
                return ResourceManager.GetString("ChangePasswordSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password.
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully deleted an invitation..
        /// </summary>
        public static string InvitationDeleteNotification {
            get {
                return ResourceManager.GetString("InvitationDeleteNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have logged off successfully!.
        /// </summary>
        public static string LogOffSuccess {
            get {
                return ResourceManager.GetString("LogOffSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email has been confirmed..
        /// </summary>
        public static string NotifyYourEmailIsConfirmed {
            get {
                return ResourceManager.GetString("NotifyYourEmailIsConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users have been defined for this action..
        /// </summary>
        public static string NoUsersHaveBeenDefined {
            get {
                return ResourceManager.GetString("NoUsersHaveBeenDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully created the organization.
        /// </summary>
        public static string OrganizationCreatedNotification {
            get {
                return ResourceManager.GetString("OrganizationCreatedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been deleted successfully..
        /// </summary>
        public static string OrganizationDeleteNotification {
            get {
                return ResourceManager.GetString("OrganizationDeleteNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization details have been updated successfully..
        /// </summary>
        public static string OrganizationDetailsUpdated {
            get {
                return ResourceManager.GetString("OrganizationDetailsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured..
        /// </summary>
        public static string StatusErrorMessage {
            get {
                return ResourceManager.GetString("StatusErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subdomain name provided has already been taken!.
        /// </summary>
        public static string SubdomainTaken {
            get {
                return ResourceManager.GetString("SubdomainTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token was not assigned properly..
        /// </summary>
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been updated..
        /// </summary>
        public static string UpdateProfileSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateProfileSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been sucessfully added..
        /// </summary>
        public static string UserAddedSuccessfully {
            get {
                return ResourceManager.GetString("UserAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already is a part of this organization!.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted successfully..
        /// </summary>
        public static string UserDeletedSuccessfully {
            get {
                return ResourceManager.GetString("UserDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been sent an email invitation..
        /// </summary>
        public static string UserEmailed {
            get {
                return ResourceManager.GetString("UserEmailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users changed roles in organization..
        /// </summary>
        public static string UsersChangedRolesInOrg {
            get {
                return ResourceManager.GetString("UsersChangedRolesInOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users changed roles in Time Tracker..
        /// </summary>
        public static string UsersChangedRolesInTimeTracker {
            get {
                return ResourceManager.GetString("UsersChangedRolesInTimeTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem signing in..
        /// </summary>
        public static string WarnProblemSigningIn {
            get {
                return ResourceManager.GetString("WarnProblemSigningIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email has already been confirmed..
        /// </summary>
        public static string WarnYourEmailHasAlreadyBeenConfirmed {
            get {
                return ResourceManager.GetString("WarnYourEmailHasAlreadyBeenConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are unable to change your own role in the organization..
        /// </summary>
        public static string YouAreUnableToChangeYourOwnRole {
            get {
                return ResourceManager.GetString("YouAreUnableToChangeYourOwnRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are unable to remove yourself from an organization..
        /// </summary>
        public static string YouAreUnableToRemoveYourself {
            get {
                return ResourceManager.GetString("YouAreUnableToRemoveYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not define a target role for the users.
        /// </summary>
        public static string YouDidNotDefineATargetRole {
            get {
                return ResourceManager.GetString("YouDidNotDefineATargetRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have a subscription to Time Tracker!.
        /// </summary>
        public static string YouDontHaveASubscriptionToTimeTracker {
            get {
                return ResourceManager.GetString("YouDontHaveASubscriptionToTimeTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Organization.
        /// </summary>
        public static string YourOrg {
            get {
                return ResourceManager.GetString("YourOrg", resourceCulture);
            }
        }
    }
}
