CREATE TABLE [StaffingManager].[Position] (
	[PositionId]					INT		         IDENTITY (123000, 3) NOT NULL,
	[OrganizationId]				INT				 CONSTRAINT [DF__Auth__OrganizationId] DEFAULT ((0)) NOT NULL,
	[CustomerId]					INT				 CONSTRAINT [DF__Crm_CustomerId] DEFAULT ((0)) NULL,
	[AddressId]						INT              CONSTRAINT [DF__Lookup_AddressId] DEFAULT ((0)) NOT NULL,
	[PositionCreatedUtc]			DATETIME2 (0)    DEFAULT (getutcdate()) NOT NULL,
	[PositionModifiedUtc]			DATETIME2 (0)    DEFAULT (getutcdate()) NOT NULL,
	[StartDate]						DATETIME2 (0)    NULL,
	[PositionStatus]				TINYINT			 NOT NULL DEFAULT ((1)),
	[PositionTitle]					NVARCHAR (140)   NOT NULL,
	[BillingRateFrequency]			INT				 NULL,
	[BillingRateAmount]				INT				 NULL,
	[DurationMonths]				INT				 NOT NULL,
	[EmploymentType]				TINYINT			 NOT NULL,
	[PoitionCount]					INT				 NOT NULL DEFAULT ((1)),
	[RequiredSkills]				NVARCHAR (MAX)   NOT NULL,
	[JobResponsibilities]			NVARCHAR (MAX)   NULL,
	[DesiredSkills]					NVARCHAR (MAX)   NULL,
	[PositionLevel]					NVARCHAR (384)   NOT NULL,
	[HiringManager]					NVARCHAR (384)   NULL,
	[TeamName]						NVARCHAR (384)   NULL,
	CONSTRAINT [PK_PositionId] PRIMARY KEY CLUSTERED ([PositionId] ASC),
	CONSTRAINT [FK_Auth_OrganizationId] FOREIGN KEY ([OrganizationId]) REFERENCES [Auth].[Organization] ([OrganizationId]),
	CONSTRAINT [FK_Lookup_AddressId] FOREIGN KEY ([AddressId]) REFERENCES [Lookup].[Address] ([AddressId]),
	CONSTRAINT [FK_Crm_CustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [Crm].[Customer] ([CustomerId]),
);

