//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllyisApps.Resources
{


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AllyisApps.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform this action..
        /// </summary>
        internal static string ActionUnauthorizedMessage {
            get {
                return ResourceManager.GetString("ActionUnauthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are too young to use this site..
        /// </summary>
        internal static string AgeTooLow {
            get {
                return ResourceManager.GetString("AgeTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  cannot be a null reference..
        /// </summary>
        internal static string ArugmentNullMessage {
            get {
                return ResourceManager.GetString("ArugmentNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are unable to edit the members of this organization..
        /// </summary>
        internal static string CannotEditMembersMessage {
            get {
                return ResourceManager.GetString("CannotEditMembersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are unable edit this organization..
        /// </summary>
        internal static string CannotEditProfileMessage {
            get {
                return ResourceManager.GetString("CannotEditProfileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are unable to edit subscriptions for this organization..
        /// </summary>
        internal static string CannotEditSubscriptionsMessage {
            get {
                return ResourceManager.GetString("CannotEditSubscriptionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are unable to view this organization..
        /// </summary>
        internal static string CannotViewProfileMessage {
            get {
                return ResourceManager.GetString("CannotViewProfileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is not within acceptable ranges..
        /// </summary>
        internal static string DateOutOfValidSQLRange {
            get {
                return ResourceManager.GetString("DateOutOfValidSQLRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already validated your email..
        /// </summary>
        internal static string EmailAlreadyValidatedMessage {
            get {
                return ResourceManager.GetString("EmailAlreadyValidatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access code provided is invalid..
        /// </summary>
        internal static string InvalidAccessCodeMessage {
            get {
                return ResourceManager.GetString("InvalidAccessCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model provided is null..
        /// </summary>
        internal static string ModelNullMessage {
            get {
                return ResourceManager.GetString("ModelNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t in an organization. Please create one or get an invite..
        /// </summary>
        internal static string NoOrganizationWhenGoingToApp {
            get {
                return ResourceManager.GetString("NoOrganizationWhenGoingToApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create or join an organization first..
        /// </summary>
        internal static string NoOrganizationWhenTryingToEditAnApp {
            get {
                return ResourceManager.GetString("NoOrganizationWhenTryingToEditAnApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified organization does not exist..
        /// </summary>
        internal static string OrganizationNonExistantMessage {
            get {
                return ResourceManager.GetString("OrganizationNonExistantMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided parameters are not valid..
        /// </summary>
        internal static string ParameterErrorMessage {
            get {
                return ResourceManager.GetString("ParameterErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password was incorrect..
        /// </summary>
        internal static string SignInFailureMessage {
            get {
                return ResourceManager.GetString("SignInFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified subscription does not exist..
        /// </summary>
        internal static string SubscriptionNonExistantMessage {
            get {
                return ResourceManager.GetString("SubscriptionNonExistantMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields of your user profile must be filled out before you can use this Allyis App..
        /// </summary>
        internal static string UserProfileIncomplete {
            get {
                return ResourceManager.GetString("UserProfileIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not subscribed to this product..
        /// </summary>
        internal static string YouAreNotSubscribedToThisProduct {
            get {
                return ResourceManager.GetString("YouAreNotSubscribedToThisProduct", resourceCulture);
            }
        }
    }
}
