//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllyisApps.Resources.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AllyisApps.Resources.Files.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Required:)	Customer Name	Customer Id		(Optional:)	Customer Street Address	Customer City	Customer Country	Customer State	Customer Postal Code	Customer Email	Customer Phone Number	Customer Fax Number	Customer EIN
        ///	ExampleCorp	CUST-0001			1234 Example st	Anytown	United States	WA	98765	contace@examplecorp.com	123-456-7890	123-456-7899	12-3456789
        ///	FakeDataCorp	CUST-0002			1111 Fake st	Fakeville	United States	WA	99999	fake@notreal.com	111-111-1111	111-111-1119	11-1111111
        ///.
        /// </summary>
        public static string CustomerProjectImportTemplate {
            get {
                return ResourceManager.GetString("CustomerProjectImportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CustomerProjectImportTemplate1 {
            get {
                object obj = ResourceManager.GetObject("CustomerProjectImportTemplate1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName,FirstName,Email
        ///Doe,Jon,jond@allyis.com
        ///Doe,Jane,janed@allyis.com
        ///Bourne,Jason,jasonb@allyis.com
        ///
        ///.
        /// </summary>
        public static string ImportUserTemplate {
            get {
                return ResourceManager.GetString("ImportUserTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This workbook explains how to import Time Entries to AllyisApps
        ///.
        /// </summary>
        public static string TimeEntryImportTemplate {
            get {
                return ResourceManager.GetString("TimeEntryImportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] TimeEntryImportTemplate1 {
            get {
                object obj = ResourceManager.GetObject("TimeEntryImportTemplate1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This workbook explains how to import Users to AllyisApps
        ///.
        /// </summary>
        public static string UserImportTemplate {
            get {
                return ResourceManager.GetString("UserImportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] UserImportTemplate1 {
            get {
                object obj = ResourceManager.GetObject("UserImportTemplate1", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
